// const forwardSlash = '/';
// const backwardSlash = r'\';
// const tabSpace = '  ';
const whiteSpace = ' ';
const asterisk = '*';
// const centerDot = '᛫';
// const emptyString = '';
// const threeDots = '...';
// const comma = ',';
// const fullStop = '.';
// const equals = '=';
// const ampersand = '&';
// const pound = '#';
// const colon = ':';
// const hyphen = '-';
// const newLine = '\n';
// const openingParenthesis = '(';
// const closingParenthesis = ')';
