package trade.sky.core.utils.enums

enum class WifiAdapterState(val value: String) {
    UNKNOWN("WIFI_ADAPTER_STATE_UNKNOWN"),
    ENABLING("WIFI_ADAPTER_STATE_TURNING_ON"),
    ENABLED("WIFI_ADAPTER_STATE_ON"),
    DISABLING("WIFI_ADAPTER_STATE_TURNING_OFF"),
    DISABLED("WIFI_ADAPTER_STATE_OFF"),
}

enum class InAppUpdateType(val value: String) {
    FLEXIBLE("FLEXIBLE_UPDATE"),
    IMMEDIATE("IMMEDIATE_UPDATE"),
    NONE("NO_UPDATE")
}

enum class InAppUpdateExecutionChainState(val value: String) {
    CHECKING_FOR_UPDATE("CHECKING_FOR_UPDATE"),
    CHECKED_FOR_UPDATE("CHECKED_FOR_UPDATE"),
    FAILED_TO_CHECK_FOR_UPDATE("FAILED_TO_CHECK_FOR_UPDATE"),
    LISTENING_UPDATE_STATE("LISTENING_UPDATE_STATE"),
    UPDATE_STATE_LISTENER_REGISTERED("UPDATE_STATE_LISTENER_REGISTERED"),
    CHECKING_AND_RESUMING_STALLED_IMMEDIATE_UPDATE_IF_ANY("CHECKING_AND_RESUMING_STALLED_IMMEDIATE_UPDATE_IF_ANY"),
    INSTALLING_FLEXIBLE_UPDATE("INSTALLING_FLEXIBLE_UPDATE"),
    UPDATE_STATE_LISTENER_UNREGISTERED("UPDATE_STATE_LISTENER_UNREGISTERED")
}

enum class InAppUpdateState(val value: String) {
    DOWNLOADING("DOWNLOADING"),
    DOWNLOADED("DOWNLOADED"),
    INSTALLING("INSTALLING"),
    INSTALLED("INSTALLED"),
    FAILED("FAILED"),
    CANCELED("CANCELED"),
    PENDING("PENDING"),
    UNKNOWN("UNKNOWN")
}