include: package:very_good_analysis/analysis_options.yaml

analyzer:
  language:
    strict-raw-types: true

  errors:
    close_sinks: error
    collection_methods_unrelated_type: error
    unrelated_type_equality_checks: error
    prefer_single_quotes: error

  exclude:
    - test/.test_coverage.dart
    - lib/generated_plugin_registrant.dart

linter:
  rules:
    public_member_api_docs: false
    prefer_single_quotes: true
    one_member_abstracts: false
