package_rename_config:
  android:
    app_name: SkyTrade
    package_name: trade.sky.utm
    override_old_package: com.skytrade.sky_ways
    lang: kotlin

  ios:
    app_name: SkyTrade
    bundle_name: utm
    override_old_package: com.skytrade.skyWays
    package_name: trade.sky.utm