package_rename_config:
  android:
    app_name: SkyTrade
    override_old_package: trade.sky
    package_name: mobile.trade.sky
    lang: kotlin

  ios:
    app_name: SkyTrade
    bundle_name: SkyTrade
    override_old_package: trade.sky
    package_name: mobile.trade.sky