package_rename_config:
  android:
    app_name: SkyTrade
    package_name: trade.sky
    override_old_package: trade.sky.utm
    lang: kotlin

  ios:
    app_name: SkyTrade
    bundle_name: sky
    override_old_package: trade.sky.utm
    package_name: trade.sky