// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:sky_trade/core/utils/adapters/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AdditionalLinkModelAdapter());
    registerAdapter(GeometryModelAdapter());
    registerAdapter(GeometryTypeAdapter());
    registerAdapter(PropertiesModelAdapter());
    registerAdapter(RestrictionModelAdapter());
    registerAdapter(RestrictionTypeAdapter());
  }
}
