// Mocks generated by Mockito 5.4.5 from annotations
// in sky_trade/test/features/auth/presentation/blocs/auth_bloc/auth_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:auth0_flutter/auth0_flutter.dart' as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sky_trade/core/errors/failures/auth_failure.dart' as _i6;
import 'package:sky_trade/core/utils/enums/ui.dart' as _i8;
import 'package:sky_trade/features/auth/domain/entities/auth_entity.dart'
    as _i7;
import 'package:sky_trade/features/auth/domain/repositories/auth_repository.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCredentials_1 extends _i1.SmartFake implements _i3.Credentials {
  _FakeCredentials_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i4.AuthRepository {
  @override
  _i5.Future<_i2.Either<_i6.Auth0UserNotFoundFailure, _i7.Auth0UserEntity>>
  get auth0User =>
      (super.noSuchMethod(
            Invocation.getter(#auth0User),
            returnValue: _i5.Future<
              _i2.Either<_i6.Auth0UserNotFoundFailure, _i7.Auth0UserEntity>
            >.value(
              _FakeEither_0<_i6.Auth0UserNotFoundFailure, _i7.Auth0UserEntity>(
                this,
                Invocation.getter(#auth0User),
              ),
            ),
            returnValueForMissingStub: _i5.Future<
              _i2.Either<_i6.Auth0UserNotFoundFailure, _i7.Auth0UserEntity>
            >.value(
              _FakeEither_0<_i6.Auth0UserNotFoundFailure, _i7.Auth0UserEntity>(
                this,
                Invocation.getter(#auth0User),
              ),
            ),
          )
          as _i5.Future<
            _i2.Either<_i6.Auth0UserNotFoundFailure, _i7.Auth0UserEntity>
          >);

  @override
  _i5.Future<bool> get auth0SessionForDeletedUserExists =>
      (super.noSuchMethod(
            Invocation.getter(#auth0SessionForDeletedUserExists),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<String?> get userEmail =>
      (super.noSuchMethod(
            Invocation.getter(#userEmail),
            returnValue: _i5.Future<String?>.value(),
            returnValueForMissingStub: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<_i2.Either<_i6.Auth0AuthenticationFailure, _i7.Auth0UserEntity>>
  authenticateUserWithAuth0() =>
      (super.noSuchMethod(
            Invocation.method(#authenticateUserWithAuth0, []),
            returnValue: _i5.Future<
              _i2.Either<_i6.Auth0AuthenticationFailure, _i7.Auth0UserEntity>
            >.value(
              _FakeEither_0<
                _i6.Auth0AuthenticationFailure,
                _i7.Auth0UserEntity
              >(this, Invocation.method(#authenticateUserWithAuth0, [])),
            ),
            returnValueForMissingStub: _i5.Future<
              _i2.Either<_i6.Auth0AuthenticationFailure, _i7.Auth0UserEntity>
            >.value(
              _FakeEither_0<
                _i6.Auth0AuthenticationFailure,
                _i7.Auth0UserEntity
              >(this, Invocation.method(#authenticateUserWithAuth0, [])),
            ),
          )
          as _i5.Future<
            _i2.Either<_i6.Auth0AuthenticationFailure, _i7.Auth0UserEntity>
          >);

  @override
  _i5.Future<_i3.Credentials> renewAuth0UserCredentialsUsing({
    required String? refreshToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#renewAuth0UserCredentialsUsing, [], {
              #refreshToken: refreshToken,
            }),
            returnValue: _i5.Future<_i3.Credentials>.value(
              _FakeCredentials_1(
                this,
                Invocation.method(#renewAuth0UserCredentialsUsing, [], {
                  #refreshToken: refreshToken,
                }),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.Credentials>.value(
              _FakeCredentials_1(
                this,
                Invocation.method(#renewAuth0UserCredentialsUsing, [], {
                  #refreshToken: refreshToken,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Credentials>);

  @override
  _i5.Future<bool> updateAuth0UserWithNew({
    required _i3.Credentials? credentials,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateAuth0UserWithNew, [], {
              #credentials: credentials,
            }),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> checkAuth0UserSessionExists() =>
      (super.noSuchMethod(
            Invocation.method(#checkAuth0UserSessionExists, []),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> setAuth0SessionForDeletedUserExists({
    required bool? value,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setAuth0SessionForDeletedUserExists, [], {
              #value: value,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.Either<_i6.Auth0LogoutFailure, _i2.Unit>>
  logoutCurrentAuth0User() =>
      (super.noSuchMethod(
            Invocation.method(#logoutCurrentAuth0User, []),
            returnValue:
                _i5.Future<_i2.Either<_i6.Auth0LogoutFailure, _i2.Unit>>.value(
                  _FakeEither_0<_i6.Auth0LogoutFailure, _i2.Unit>(
                    this,
                    Invocation.method(#logoutCurrentAuth0User, []),
                  ),
                ),
            returnValueForMissingStub:
                _i5.Future<_i2.Either<_i6.Auth0LogoutFailure, _i2.Unit>>.value(
                  _FakeEither_0<_i6.Auth0LogoutFailure, _i2.Unit>(
                    this,
                    Invocation.method(#logoutCurrentAuth0User, []),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Auth0LogoutFailure, _i2.Unit>>);

  @override
  _i5.Future<_i2.Either<_i6.SFAConfigurationFailure, _i2.Unit>>
  configureSFA() =>
      (super.noSuchMethod(
            Invocation.method(#configureSFA, []),
            returnValue: _i5.Future<
              _i2.Either<_i6.SFAConfigurationFailure, _i2.Unit>
            >.value(
              _FakeEither_0<_i6.SFAConfigurationFailure, _i2.Unit>(
                this,
                Invocation.method(#configureSFA, []),
              ),
            ),
            returnValueForMissingStub: _i5.Future<
              _i2.Either<_i6.SFAConfigurationFailure, _i2.Unit>
            >.value(
              _FakeEither_0<_i6.SFAConfigurationFailure, _i2.Unit>(
                this,
                Invocation.method(#configureSFA, []),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.SFAConfigurationFailure, _i2.Unit>>);

  @override
  _i5.Future<_i2.Either<_i6.SFAInitializationFailure, _i2.Unit>>
  initializeSFA() =>
      (super.noSuchMethod(
            Invocation.method(#initializeSFA, []),
            returnValue: _i5.Future<
              _i2.Either<_i6.SFAInitializationFailure, _i2.Unit>
            >.value(
              _FakeEither_0<_i6.SFAInitializationFailure, _i2.Unit>(
                this,
                Invocation.method(#initializeSFA, []),
              ),
            ),
            returnValueForMissingStub: _i5.Future<
              _i2.Either<_i6.SFAInitializationFailure, _i2.Unit>
            >.value(
              _FakeEither_0<_i6.SFAInitializationFailure, _i2.Unit>(
                this,
                Invocation.method(#initializeSFA, []),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.SFAInitializationFailure, _i2.Unit>>);

  @override
  _i5.Future<_i2.Either<_i6.SFAAuthenticationFailure, _i7.SFAUserEntity>>
  authenticateAuth0UserWithSFAUsing({
    required String? email,
    required String? idToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#authenticateAuth0UserWithSFAUsing, [], {
              #email: email,
              #idToken: idToken,
            }),
            returnValue: _i5.Future<
              _i2.Either<_i6.SFAAuthenticationFailure, _i7.SFAUserEntity>
            >.value(
              _FakeEither_0<_i6.SFAAuthenticationFailure, _i7.SFAUserEntity>(
                this,
                Invocation.method(#authenticateAuth0UserWithSFAUsing, [], {
                  #email: email,
                  #idToken: idToken,
                }),
              ),
            ),
            returnValueForMissingStub: _i5.Future<
              _i2.Either<_i6.SFAAuthenticationFailure, _i7.SFAUserEntity>
            >.value(
              _FakeEither_0<_i6.SFAAuthenticationFailure, _i7.SFAUserEntity>(
                this,
                Invocation.method(#authenticateAuth0UserWithSFAUsing, [], {
                  #email: email,
                  #idToken: idToken,
                }),
              ),
            ),
          )
          as _i5.Future<
            _i2.Either<_i6.SFAAuthenticationFailure, _i7.SFAUserEntity>
          >);

  @override
  _i5.Future<bool> checkSFAUserSessionExists() =>
      (super.noSuchMethod(
            Invocation.method(#checkSFAUserSessionExists, []),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<_i2.Either<_i6.SFALogoutFailure, _i2.Unit>>
  logoutCurrentSFAUser() =>
      (super.noSuchMethod(
            Invocation.method(#logoutCurrentSFAUser, []),
            returnValue:
                _i5.Future<_i2.Either<_i6.SFALogoutFailure, _i2.Unit>>.value(
                  _FakeEither_0<_i6.SFALogoutFailure, _i2.Unit>(
                    this,
                    Invocation.method(#logoutCurrentSFAUser, []),
                  ),
                ),
            returnValueForMissingStub:
                _i5.Future<_i2.Either<_i6.SFALogoutFailure, _i2.Unit>>.value(
                  _FakeEither_0<_i6.SFALogoutFailure, _i2.Unit>(
                    this,
                    Invocation.method(#logoutCurrentSFAUser, []),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.SFALogoutFailure, _i2.Unit>>);

  @override
  _i5.Future<_i2.Either<_i6.CreateSkyTradeUserFailure, _i7.SkyTradeUserEntity>>
  createSkyTradeUserUsing({
    required String? phoneNumber,
    required _i8.UserCategory? userCategory,
    required bool? subscribeToNewsletter,
    required String? referralCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createSkyTradeUserUsing, [], {
              #phoneNumber: phoneNumber,
              #userCategory: userCategory,
              #subscribeToNewsletter: subscribeToNewsletter,
              #referralCode: referralCode,
            }),
            returnValue: _i5.Future<
              _i2.Either<_i6.CreateSkyTradeUserFailure, _i7.SkyTradeUserEntity>
            >.value(
              _FakeEither_0<
                _i6.CreateSkyTradeUserFailure,
                _i7.SkyTradeUserEntity
              >(
                this,
                Invocation.method(#createSkyTradeUserUsing, [], {
                  #phoneNumber: phoneNumber,
                  #userCategory: userCategory,
                  #subscribeToNewsletter: subscribeToNewsletter,
                  #referralCode: referralCode,
                }),
              ),
            ),
            returnValueForMissingStub: _i5.Future<
              _i2.Either<_i6.CreateSkyTradeUserFailure, _i7.SkyTradeUserEntity>
            >.value(
              _FakeEither_0<
                _i6.CreateSkyTradeUserFailure,
                _i7.SkyTradeUserEntity
              >(
                this,
                Invocation.method(#createSkyTradeUserUsing, [], {
                  #phoneNumber: phoneNumber,
                  #userCategory: userCategory,
                  #subscribeToNewsletter: subscribeToNewsletter,
                  #referralCode: referralCode,
                }),
              ),
            ),
          )
          as _i5.Future<
            _i2.Either<_i6.CreateSkyTradeUserFailure, _i7.SkyTradeUserEntity>
          >);

  @override
  _i5.Future<_i2.Either<_i6.CheckSkyTradeUserFailure, _i7.SkyTradeUserEntity>>
  checkSkyTradeUserExists() =>
      (super.noSuchMethod(
            Invocation.method(#checkSkyTradeUserExists, []),
            returnValue: _i5.Future<
              _i2.Either<_i6.CheckSkyTradeUserFailure, _i7.SkyTradeUserEntity>
            >.value(
              _FakeEither_0<
                _i6.CheckSkyTradeUserFailure,
                _i7.SkyTradeUserEntity
              >(this, Invocation.method(#checkSkyTradeUserExists, [])),
            ),
            returnValueForMissingStub: _i5.Future<
              _i2.Either<_i6.CheckSkyTradeUserFailure, _i7.SkyTradeUserEntity>
            >.value(
              _FakeEither_0<
                _i6.CheckSkyTradeUserFailure,
                _i7.SkyTradeUserEntity
              >(this, Invocation.method(#checkSkyTradeUserExists, [])),
            ),
          )
          as _i5.Future<
            _i2.Either<_i6.CheckSkyTradeUserFailure, _i7.SkyTradeUserEntity>
          >);
}
