publisher:
  name: SkyTradeLinks
  address: 7SFBHqJDgApc1spibrCQ6UviUbf7mujLZmk1ERQgvmJ8
  website: https://sky.trade
  email: help@sky.trade
  media:
    - purpose: icon
      uri: ../fastlane/metadata/android/en-GB/images/icon.png
app:
  name: SkyTrade
  address: 5SVmstv15fb11c55ndEzWPjuuBaQ74tPqTGXpsAvLhhb
  android_package: mobile.trade.sky
  urls:
    license_url: https://docs.sky.trade/terms.htm
    copyright_url: https://sky.trade
    privacy_policy_url: https://docs.sky.trade/privacy.htm
    website: https://sky.trade
  media:
    - purpose: icon
      uri: ../fastlane/metadata/android/en-GB/images/icon.png
release:
  address: 252EWVh8C2K8eeHgTBWTGZPSmqKqf1CR9736zKR7573q
  media:
    - purpose: icon
      uri: ../fastlane/metadata/android/en-GB/images/icon.png
    - purpose: screenshot
      uri: ../fastlane/metadata/android/en-GB/images/phoneScreenshots/1_en-GB.png
    - purpose: screenshot
      uri: ../fastlane/metadata/android/en-GB/images/phoneScreenshots/2_en-GB.png
    - purpose: screenshot
      uri: ../fastlane/metadata/android/en-GB/images/phoneScreenshots/3_en-GB.png
    - purpose: screenshot
      uri: ../fastlane/metadata/android/en-GB/images/phoneScreenshots/4_en-GB.png
  files:
    - purpose: install
      uri: ../../build/app/outputs/flutter-apk/app-live-release.apk
  catalog:
    en-US:
      name: SkyTrade
      short_description: Navigate the skies
      long_description: Navigate the skies with confidence using SkyTrade Air Management. Instantly access maps of restricted, controlled, and ready-to-fly zones with real-time updates. Plan your flights efficiently with detailed airspace information and stay compliant with aviation regulations. Download now for smarter, safer flying
      new_in_version: We made a couple of bug fixes and improvements
      saga_features: ''
solana_mobile_dapp_publisher_portal:
  google_store_package: mobile.trade.sky
  testing_instructions: We refined our authentication flow. The new flow simplifies authentication for users making it easy for both new and existing users to sign up or sign in. We created a test account for the Solana dApp store review team to test this new flow easily. On the new authentication screen, click Get started -> Use password -> then enter the following credentials we specially created for the Solana dApp store review team to test with. Email is testrestrictionsapp+solanadappstorereview@gmail.com and password is Shivam##%27
lastSubmittedVersionOnChain:
  address: 252EWVh8C2K8eeHgTBWTGZPSmqKqf1CR9736zKR7573q
  version_code: 7
  apk_hash: Yt0dosmPoZKTDb+dJMy+3ocng5lEpH3zhtn9hb1UPJU=
lastUpdatedVersionOnStore:
  address: 252EWVh8C2K8eeHgTBWTGZPSmqKqf1CR9736zKR7573q
