package mobile.trade.sky.core.utils.constants

const val WIFI_ADAPTER_STATE_BROADCAST_RECEIVER_CHANNEL_NAME =
    "WIFI_ADAPTER_STATE_BROADCAST_RECEIVER_CHANNEL"

const val IN_APP_UPDATE_CHANNEL_NAME = "IN_APP_UPDATE_CHANNEL"
const val CHECK_AND_START_UPDATE_METHOD_CALL = "CHECK_AND_START_UPDATE"
const val REGISTER_UPDATE_STATE_LISTENER_AND_CHECK_AND_RESUME_STALLED_IMMEDIATE_UPDATE_IF_ANY_METHOD_CALL =
    "REGISTER_UPDATE_STATE_LISTENER_AND_CHECK_AND_RESUME_STALLED_IMMEDIATE_UPDATE_IF_ANY"
const val INSTALL_FLEXIBLE_UPDATE_METHOD_CALL = "INSTALL_FLEXIBLE_UPDATE"
const val UNREGISTER_UPDATE_STATE_LISTENER_METHOD_CALL = "UNREGISTER_UPDATE_STATE_LISTENER"
const val IN_APP_UPDATE_REQUEST_CODE = 123
const val FLEXIBLE_UPDATE_MAX_PRIORITY = 2
const val FLEXIBLE_UPDATE_MAX_STALENESS_DAYS = 31