default_platform(:android)

platform :android do
  desc "Deploy live release app bundle to Playstore"
  lane :deploy do
    clean()

    update_version_name()

    update_version_code()

    build_app_bundle()

    deploy_to_playstore()
  end

  desc "Clean project"
  lane :clean do
    gradle(task: "clean assembleLiveRelease")
  end

  desc "Update version name"
  lane :update_version_name do
    increment_version_name(
      app_project_dir: ENV["APP_DIRECTORY"],
      bump_type: "patch"
    )
  end

  desc "Update version code"
  lane :update_version_code do
    existing_build_number = google_play_track_version_codes(
      track: "production",
    )[0]

    new_build_number = existing_build_number + 1

    increment_version_code(
      app_project_dir: ENV["APP_DIRECTORY"],
      version_code: new_build_number
    )
  end

  desc "Build live release app bundle"
  lane :build_app_bundle do
    sh "flutter build appbundle --flavor live"
  end

  desc "Deploy to Playstore"
  lane :deploy_to_playstore do
    upload_to_play_store(
      aab: ENV["APP_BUNDLE"],
      in_app_update_priority: 0,
      skip_upload_apk: true,
      skip_upload_aab: false,
      skip_upload_metadata: true,
      skip_upload_changelogs: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end
